### ISSUE TITLE
vanilla/index.html proposé à la fin du contenu DOM

### ISSUE THREAD

**Issue by DavidBruant** [bleucitron/formation#4]
Est-ce qu'il ne faudrait pas plutôt envoyer sur exercice/tweets.html d'abord ?

(rienàv) Est-ce que le fichier `vanilla/index.html` devrait être déplacé dans le dossier des exercices ?

**Comment by bleucitron** [comment]
En fait le `exercice/tweets.html` je leur fais faire juste avec le pense bete DOM intégré au début du fichier, et après ça je présente la partie DOM.

Pour le 2e point, je pense qu'il faudrait mettre `vanilla/index.html` à la racine, parce que quand je fais les exos dans `react/`, ca permet de réutiliser le même fichier sans avoir à le déplacer ou le copier.
